---

services:
  fastapi_app:
    image: us-west1-docker.pkg.dev/wizeline-deb/gamma-docker-repo/uchemadu/gamma-youtube-summarizer
    container_name: gamma-youtube-summarizer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8000"
    env_file:
      - .env
    volumes:
      - ./docker-youtube-summarizer:/app/assets


