# app/config.py
from decouple import config
from dotenv import load_dotenv

load_dotenv()

SERPAPI_API_KEY = config("SERPAPI_API_KEY")
# GROQ_API_KEY = config("GROQ_API_KEY")
TOGETHER_API_KEY = config("TOGETHER_API_KEY")
MODEL_NAME = "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo"

WEBSHARE_PROXY_USERNAME = config("WEBSHARE_PROXY_USERNAME")
WEBSHARE_PROXY_PASSWORD = config("WEBSHARE_PROXY_PASSWORD")
WEBSHARE_PROXY_PORT = config("WEBSHARE_PROXY_PORT")
WEBSHARE_PROXY_ADDRESS = config("WEBSHARE_PROXY_ADDRESS")

WEBSHARE_PROXY_HTTP_URL = f"http://{WEBSHARE_PROXY_USERNAME}:{WEBSHARE_PROXY_PASSWORD}@{WEBSHARE_PROXY_ADDRESS}:{WEBSHARE_PROXY_PORT}"
WEBSHARE_PROXY_HTTPS_URL = f"https://{WEBSHARE_PROXY_USERNAME}:{WEBSHARE_PROXY_PASSWORD}@{WEBSHARE_PROXY_ADDRESS}:{WEBSHARE_PROXY_PORT}"

WEBSHARE_PROXY_CONFIG = {
    "http_url": WEBSHARE_PROXY_HTTP_URL,
    "https_url": WEBSHARE_PROXY_HTTPS_URL,
}
